In [ ]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

# Reading Dataset

In [ ]:
df=pd.read_csv("Myocardial infarction complications.csv")

In [ ]:
df.drop('ID',
  axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1700 entries, 0 to 1699
Columns: 123 entries, AGE to LET_IS
dtypes: float64(110), int64(13)
memory usage: 1.6 MB


In [ ]:
df

AGE  SEX  INF_ANAM  STENOK_AN  ...  ZSN  REC_IM  P_IM_STEN  LET_IS
0     77.0    1       2.0        1.0  ...    0       0          0       0
1     55.0    1       1.0        0.0  ...    0       0          0       0
2     52.0    1       0.0        0.0  ...    0       0          0       0
3     68.0    0       0.0        0.0  ...    1       0          0       0
4     60.0    1       0.0        0.0  ...    0       0          0       0
...    ...  ...       ...        ...  ...  ...     ...        ...     ...
1695  77.0    0       0.0        4.0  ...    0       0          0       3
1696  70.0    0       0.0        6.0  ...    0       0          0       1
1697  55.0    1       3.0        6.0  ...    0       1          0       6
1698  79.0    0       2.0        2.0  ...    0       0          0       1
1699  63.0    1       2.0        NaN  ...    0       0          0       1

[1700 rows x 123 columns]

In [ ]:
missing_list=df.isnull().sum().tolist()

# Counting null values for continuous values

In [ ]:
b=[]
cont=["AGE","S_AD_KBRIG","D_AD_KBRIG","S_AD_ORIT","D_AD_ORIT","K_BLOOD","NA_BLOOD","ALT_BLOOD","AST_BLOOD","KFK_BLOOD","L_BLOOD","ROE"]
for i in cont:
    a=df[i].isnull().sum()
    b.append(a)
b

[8, 1076, 1076, 267, 267, 371, 375, 284, 285, 1696, 125, 203]

In [ ]:
missing_list

[8,
 0,
 4,
 106,
 73,
 51,
 1628,
 9,
 8,
 248,
 54,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 11,
 10,
 10,
 7,
 7,
 7,
 7,
 7,
 1076,
 1076,
 267,
 267,
 12,
 15,
 14,
 12,
 12,
 12,
 83,
 80,
 80,
 72,
 1,
 152,
 152,
 152,
 152,
 152,
 152,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 115,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 369,
 371,
 375,
 375,
 284,
 285,
 1696,
 125,
 203,
 126,
 16,
 108,
 128,
 657,
 686,
 677,
 9,
 5,
 108,
 131,
 10,
 110,
 131,
 10,
 11,
 13,
 17,
 17,
 16,
 16,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [ ]:
df.columns.to_list()

['AGE',
 'SEX',
 'INF_ANAM',
 'STENOK_AN',
 'FK_STENOK',
 'IBS_POST',
 'IBS_NASL',
 'GB',
 'SIM_GIPERT',
 'DLIT_AG',
 'ZSN_A',
 'nr_11',
 'nr_01',
 'nr_02',
 'nr_03',
 'nr_04',
 'nr_07',
 'nr_08',
 'np_01',
 'np_04',
 'np_05',
 'np_07',
 'np_08',
 'np_09',
 'np_10',
 'endocr_01',
 'endocr_02',
 'endocr_03',
 'zab_leg_01',
 'zab_leg_02',
 'zab_leg_03',
 'zab_leg_04',
 'zab_leg_06',
 'S_AD_KBRIG',
 'D_AD_KBRIG',
 'S_AD_ORIT',
 'D_AD_ORIT',
 'O_L_POST',
 'K_SH_POST',
 'MP_TP_POST',
 'SVT_POST',
 'GT_POST',
 'FIB_G_POST',
 'ant_im',
 'lat_im',
 'inf_im',
 'post_im',
 'IM_PG_P',
 'ritm_ecg_p_01',
 'ritm_ecg_p_02',
 'ritm_ecg_p_04',
 'ritm_ecg_p_06',
 'ritm_ecg_p_07',
 'ritm_ecg_p_08',
 'n_r_ecg_p_01',
 'n_r_ecg_p_02',
 'n_r_ecg_p_03',
 'n_r_ecg_p_04',
 'n_r_ecg_p_05',
 'n_r_ecg_p_06',
 'n_r_ecg_p_08',
 'n_r_ecg_p_09',
 'n_r_ecg_p_10',
 'n_p_ecg_p_01',
 'n_p_ecg_p_03',
 'n_p_ecg_p_04',
 'n_p_ecg_p_05',
 'n_p_ecg_p_06',
 'n_p_ecg_p_07',
 'n_p_ecg_p_08',
 'n_p_ecg_p_09',
 'n_p_ecg_p_10',
 'n_p

# Making list of Categorical and continous varibale for imputataions

In [ ]:
continuous_param_list=["AGE","S_AD_KBRIG","D_AD_KBRIG","S_AD_ORIT","D_AD_ORIT","K_BLOOD","NA_BLOOD","ALT_BLOOD","AST_BLOOD","KFK_BLOOD","L_BLOOD","ROE"]

In [ ]:
len(continuous_param_list)

12

In [ ]:
categorical_param_list=[ 'SEX','INF_ANAM','STENOK_AN','FK_STENOK','IBS_POST','IBS_NASL','GB','SIM_GIPERT','DLIT_AG','ZSN_A',
'nr_11','nr_01','nr_02','nr_03','nr_04','nr_07','nr_08','np_01','np_04','np_05','np_07',
 'np_08',
 'np_09',
 'np_10',
 'endocr_01',
 'endocr_02',
 'endocr_03',
 'zab_leg_01',
 'zab_leg_02',
 'zab_leg_03',
 'zab_leg_04',
 'zab_leg_06',
 'O_L_POST',
 'K_SH_POST',
 'MP_TP_POST',
 'SVT_POST',
 'GT_POST',
 'FIB_G_POST',
 'ant_im',
 'lat_im',
 'inf_im',
 'post_im',
 'IM_PG_P',
 'ritm_ecg_p_01',
 'ritm_ecg_p_02',
 'ritm_ecg_p_04',
 'ritm_ecg_p_06',
 'ritm_ecg_p_07',
 'ritm_ecg_p_08',
 'n_r_ecg_p_01',
 'n_r_ecg_p_02',
 'n_r_ecg_p_03',
 'n_r_ecg_p_04',
 'n_r_ecg_p_05',
 'n_r_ecg_p_06',
 'n_r_ecg_p_08',
 'n_r_ecg_p_09',
 'n_r_ecg_p_10',
 'n_p_ecg_p_01',
 'n_p_ecg_p_03',
 'n_p_ecg_p_04',
 'n_p_ecg_p_05',
 'n_p_ecg_p_06',
 'n_p_ecg_p_07',
 'n_p_ecg_p_08',
 'n_p_ecg_p_09',
 'n_p_ecg_p_10',
 'n_p_ecg_p_11',
 'n_p_ecg_p_12',
 'fibr_ter_01',
 'fibr_ter_02',
 'fibr_ter_03',
 'fibr_ter_05',
 'fibr_ter_06',
 'fibr_ter_07',
 'fibr_ter_08',
 'GIPO_K',
 'GIPER_NA',
 'TIME_B_S',
 'R_AB_1_n',
 'R_AB_2_n',
 'R_AB_3_n',
 'NA_KB',
 'NOT_NA_KB',
 'LID_KB',
 'NITR_S',
 'NA_R_1_n',
 'NA_R_2_n',
 'NA_R_3_n',
 'NOT_NA_1_n',
 'NOT_NA_2_n',
 'NOT_NA_3_n',
 'LID_S_n',
 'B_BLOK_S_n',
 'ANT_CA_S_n',
 'GEPAR_S_n',
 'ASP_S_n',
 'TIKL_S_n',
 'TRENT_S_n',
 'FIBR_PREDS',
 'PREDS_TAH',
 'JELUD_TAH',
 'FIBR_JELUD',
 'A_V_BLOK',
 'OTEK_LANC',
 'RAZRIV',
 'DRESSLER',
 'ZSN',
 'REC_IM',
 'P_IM_STEN',
 'LET_IS']


In [ ]:
len(categorical_param_list)

111

# Median imputation for continuous values

In [ ]:
for column in continuous_param_list:
    df[column].fillna(df[column].median(),inplace=True)


# Mode Imputation for categorical values 

In [ ]:
for column in categorical_param_list:
    df[column].fillna(df[column].mode()[0],inplace=True)

In [ ]:
missing_list=df.isnull().sum().tolist()

In [ ]:
missing_list.count(0)

123

In [ ]:
df['S_AD_KBRIG'].isin([140]).sum()

1167

In [ ]:
df['K_BLOOD'].isin([4.1]).sum()

433

In [ ]:
df['IBS_POST'].isin([2]).sum()

734

In [ ]:
df['SIM_GIPERT'].isin([0]).sum()

1643

In [ ]:
df['DLIT_AG'].isin([0]).sum()

799

In [ ]:
df.dtypes

AGE          float64
SEX            int64
INF_ANAM     float64
STENOK_AN    float64
FK_STENOK    float64
              ...   
DRESSLER       int64
ZSN            int64
REC_IM         int64
P_IM_STEN      int64
LET_IS         int64
Length: 123, dtype: object

In [ ]:
df_new = df['LET_IS']
df_new

0       0
1       0
2       0
3       0
4       0
       ..
1695    3
1696    1
1697    6
1698    1
1699    1
Name: LET_IS, Length: 1700, dtype: int64

# Function for normalizing continuous data 

In [ ]:
for column in continuous_param_list:
    df[column] = (df[column] - df[column].min()) / (df[column].max() - df[column].min())

In [ ]:
df

AGE  SEX  INF_ANAM  STENOK_AN  ...  ZSN  REC_IM  P_IM_STEN  LET_IS
0     0.772727    1       2.0        1.0  ...    0       0          0       0
1     0.439394    1       1.0        0.0  ...    0       0          0       0
2     0.393939    1       0.0        0.0  ...    0       0          0       0
3     0.636364    0       0.0        0.0  ...    1       0          0       0
4     0.515152    1       0.0        0.0  ...    0       0          0       0
...        ...  ...       ...        ...  ...  ...     ...        ...     ...
1695  0.772727    0       0.0        4.0  ...    0       0          0       3
1696  0.666667    0       0.0        6.0  ...    0       0          0       1
1697  0.439394    1       3.0        6.0  ...    0       1          0       6
1698  0.803030    0       2.0        2.0  ...    0       0          0       1
1699  0.560606    1       2.0        0.0  ...    0       0          0       1

[1700 rows x 123 columns]

# Feature Engg using chi2

In [ ]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
column_list = df.columns.tolist()

In [ ]:
column_list.remove('LET_IS')
len(column_list)

122

In [ ]:
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, y)
fit.scores_

array([4.62026571e+00, 1.51030943e+01, 5.02338566e+01, 7.74634517e+01,
       4.33239412e+01, 3.07487375e+01, 5.12036389e+00, 1.90291182e+01,
       9.37589009e+00, 7.23900437e+01, 2.50976114e+02, 6.36360820e+00,
       2.22878081e+01, 4.18587642e+00, 1.26414813e+01, 5.32513073e+01,
       1.89643107e-01, 2.54033335e+00, 1.43355623e+01, 3.73770596e+00,
       5.53884306e+00, 1.89643107e-01, 1.54888799e+01, 3.79286214e-01,
       2.71857440e+01, 2.63512347e+01, 2.09257152e+01, 1.36639637e+00,
       7.81213774e+00, 3.42825939e+01, 2.32529066e+01, 4.34563267e+00,
       2.54941617e+00, 1.38312180e+00, 1.21381147e+00, 5.34763010e+00,
       5.01767110e+00, 6.68483562e+01, 5.21733122e+02, 5.29168988e+01,
       2.88348755e+01, 1.21838221e+00, 1.87698259e+01, 6.86391688e+01,
       2.84660378e+01, 9.75271324e+00, 6.69603632e+00, 4.79146935e+01,
       2.83532451e+01, 6.36891156e+01, 3.24294622e+01, 1.89643107e-01,
       4.23017727e+01, 3.24303941e+00, 4.92193658e+00, 7.15693440e+00,
      

In [ ]:
len(fit.scores_)

122

# Making dict of score and feature  using df.columns as list and chi2 score as values as to get idea of weights of each columns

In [ ]:
d=dict();
for i in range(len(fit.scores_)):
    d[column_list[i]]= fit.scores_[i]

In [ ]:
d

{'AGE': 4.620265712697622,
 'ALT_BLOOD': 1.4793908736773749,
 'ANT_CA_S_n': 22.808019280447276,
 'ASP_S_n': 23.93723250932277,
 'AST_BLOOD': 1.5657944943166395,
 'A_V_BLOK': 15.426510985802848,
 'B_BLOK_S_n': 13.551458774832616,
 'DLIT_AG': 72.3900437314849,
 'DRESSLER': 8.693451425851705,
 'D_AD_KBRIG': 1.2138114652988918,
 'D_AD_ORIT': 5.01767109990906,
 'FIBR_JELUD': 130.65135775174016,
 'FIBR_PREDS': 12.312083420794291,
 'FIB_G_POST': 18.7698258570055,
 'FK_STENOK': 43.32394124440978,
 'GB': 19.029118180963344,
 'GEPAR_S_n': 7.335569169310554,
 'GIPER_NA': 3.621009881098521,
 'GIPO_K': 6.060271935509318,
 'GT_POST': 1.2183822126089443,
 'IBS_NASL': 5.12036389083275,
 'IBS_POST': 30.74873753634574,
 'IM_PG_P': 47.914693470746656,
 'INF_ANAM': 50.23385658922355,
 'JELUD_TAH': 9.795939332678312,
 'KFK_BLOOD': 0.000296781075223443,
 'K_BLOOD': 0.4248056863742206,
 'K_SH_POST': 521.7331222387054,
 'LID_KB': 8.956205904162129,
 'LID_S_n': 5.022234326612516,
 'L_BLOOD': 2.920920648197848,

# Filtering the dict based on values of score you wish to have among the chi2 predicted scores eg- 10,15,20

In [ ]:
high_score_features={k:v for (k,v) in d.items() if v > 15}

In [ ]:
high_score_features

{'ANT_CA_S_n': 22.808019280447276,
 'ASP_S_n': 23.93723250932277,
 'A_V_BLOK': 15.426510985802848,
 'DLIT_AG': 72.3900437314849,
 'FIBR_JELUD': 130.65135775174016,
 'FIB_G_POST': 18.7698258570055,
 'FK_STENOK': 43.32394124440978,
 'GB': 19.029118180963344,
 'IBS_POST': 30.74873753634574,
 'IM_PG_P': 47.914693470746656,
 'INF_ANAM': 50.23385658922355,
 'K_SH_POST': 521.7331222387054,
 'MP_TP_POST': 52.916898825161205,
 'NA_R_1_n': 63.667543590886034,
 'NA_R_3_n': 57.37316590056685,
 'NITR_S': 94.03762074572715,
 'NOT_NA_1_n': 17.343056706451517,
 'NOT_NA_2_n': 22.976308516869306,
 'NOT_NA_3_n': 44.793308425889826,
 'OTEK_LANC': 68.01100208510672,
 'O_L_POST': 66.84835617972199,
 'P_IM_STEN': 26.121357186437663,
 'RAZRIV': 1646.0,
 'REC_IM': 40.340167153328,
 'R_AB_1_n': 32.04759974707354,
 'R_AB_3_n': 87.4762493973921,
 'SEX': 15.103094326907588,
 'STENOK_AN': 77.46345173959232,
 'SVT_POST': 28.834875463286945,
 'TIME_B_S': 78.90039443038447,
 'ZSN': 80.19350995929126,
 'ZSN_A': 250.976

In [ ]:
len(high_score_features)

53

In [ ]:
selected_features = []
for k,v in high_score_features.items():
    selected_features.append(k)
selected_features

['SEX',
 'INF_ANAM',
 'STENOK_AN',
 'FK_STENOK',
 'IBS_POST',
 'GB',
 'DLIT_AG',
 'ZSN_A',
 'nr_01',
 'nr_04',
 'np_08',
 'np_10',
 'endocr_01',
 'endocr_02',
 'zab_leg_02',
 'zab_leg_03',
 'O_L_POST',
 'K_SH_POST',
 'MP_TP_POST',
 'SVT_POST',
 'FIB_G_POST',
 'ant_im',
 'lat_im',
 'IM_PG_P',
 'ritm_ecg_p_01',
 'ritm_ecg_p_02',
 'ritm_ecg_p_04',
 'ritm_ecg_p_07',
 'n_r_ecg_p_04',
 'n_r_ecg_p_05',
 'n_r_ecg_p_06',
 'n_p_ecg_p_03',
 'n_p_ecg_p_06',
 'n_p_ecg_p_08',
 'n_p_ecg_p_12',
 'TIME_B_S',
 'R_AB_1_n',
 'R_AB_3_n',
 'NITR_S',
 'NA_R_1_n',
 'NA_R_3_n',
 'NOT_NA_1_n',
 'NOT_NA_2_n',
 'NOT_NA_3_n',
 'ANT_CA_S_n',
 'ASP_S_n',
 'FIBR_JELUD',
 'A_V_BLOK',
 'OTEK_LANC',
 'RAZRIV',
 'ZSN',
 'REC_IM',
 'P_IM_STEN']

# Making Data set Compatible with Feature Engg selected features only and dropping rest features automatically and no updation from user needed

In [ ]:
for i in df.columns:
    if i not in selected_features:
        df.drop(i,axis=1, inplace=True)
    else:
        pass

In [ ]:
df['LET_IS'] = df_new

In [ ]:
df

SEX  INF_ANAM  STENOK_AN  FK_STENOK  ...  ZSN  REC_IM  P_IM_STEN  LET_IS
0       1       2.0        1.0        1.0  ...    0       0          0       0
1       1       1.0        0.0        0.0  ...    0       0          0       0
2       1       0.0        0.0        0.0  ...    0       0          0       0
3       0       0.0        0.0        0.0  ...    1       0          0       0
4       1       0.0        0.0        0.0  ...    0       0          0       0
...   ...       ...        ...        ...  ...  ...     ...        ...     ...
1695    0       0.0        4.0        2.0  ...    0       0          0       3
1696    0       0.0        6.0        2.0  ...    0       0          0       1
1697    1       3.0        6.0        2.0  ...    0       1          0       6
1698    0       2.0        2.0        2.0  ...    0       0          0       1
1699    1       2.0        0.0        2.0  ...    0       0          0       1

[1700 rows x 54 columns]

In [ ]:
a=df.isnull().sum()
a.sum()

0

# Checking balance for y which shows large imbalance and we need dataset balancing for it 

In [ ]:
df.LET_IS.value_counts()

0    1429
1     110
3      54
7      27
6      27
4      23
2      18
5      12
Name: LET_IS, dtype: int64

# Balancing imbalanced dataset for train set only

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
x_train, x_test, y_train, y_test = train_test_split(df.drop(labels=['LET_IS'], axis=1),df['LET_IS'],test_size=0.2,random_state=41)


# ## Train dataset balancing

from imblearn.over_sampling import SMOTE
sm = SMOTE()
x_train_res, y_train_res = sm.fit_resample(x_train, y_train)
unique, counts = np.unique(y_train_res, return_counts=True)
print(list(zip(unique, counts)))
#y_train_res
#X_train_res

[(0, 1140), (1, 1140), (2, 1140), (3, 1140), (4, 1140), (5, 1140), (6, 1140), (7, 1140)]


# Decision Tree  method

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(criterion = 'entropy',max_depth=10)
dtree.fit(x_train_res, y_train_res)
# Test Accuracy,confusion matrix, classification report
y_pred_DT_test=dtree.predict(x_test)
print ('Accuracy test:', accuracy_score(y_test, y_pred_DT_test))
print ('Confusion matrix:', confusion_matrix(y_test, y_pred_DT_test))
print ('classification report test:', classification_report(y_test, y_pred_DT_test))
# Train Accuracy
y_pred_DT_train=dtree.predict(x_train_res)
print ('Accuracy train:', accuracy_score(y_train_res, y_pred_DT_train))

Accuracy test: 0.8088235294117647
Confusion matrix: [[250  15   0   0   7   3  12   2]
 [  8  10   1   0   0   0   1   2]
 [  3   0   0   0   1   0   0   0]
 [  0   0   0  13   0   0   0   0]
 [  4   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   1   0]
 [  2   0   0   0   0   0   1   0]
 [  2   0   0   0   0   0   0   1]]
classification report test:               precision    recall  f1-score   support

           0       0.93      0.87      0.89       289
           1       0.40      0.45      0.43        22
           2       0.00      0.00      0.00         4
           3       1.00      1.00      1.00        13
           4       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         2
           6       0.07      0.33      0.11         3
           7       0.20      0.33      0.25         3

    accuracy                           0.81       340
   macro avg       0.32      0.37      0.34       340
weighted avg       0.85      0.81      0.83

# Finding optimum value of max_depth for improving accuracy for DT using Gridsearch CV on train balanced dataset

In [ ]:
from sklearn.model_selection import GridSearchCV
max_depth = np.array(range(1,10))
param_grid = dict(max_depth=max_depth)
model = DecisionTreeClassifier(criterion = 'entropy')
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid.fit(x_train_res, y_train_res)
print(grid.best_score_)
print(grid.best_params_)

0.8763157894736843
{'max_depth': 9}


# KNN Method 

In [ ]:
model_KNN = KNeighborsClassifier(n_neighbors=2)
model_KNN.fit(x_train_res, y_train_res)
# Test Accuracy,confusion matrix, classification report
y_pred_KNN_test=model_KNN.predict(x_test)
print ('Accuracy test:', accuracy_score(y_test, y_pred_KNN_test))
print ('Confusion matrix test:', confusion_matrix(y_test, y_pred_KNN_test))
print ('classification report test:', classification_report(y_test, y_pred_KNN_test))
# Train Accuracy
y_pred_KNN_train=model_KNN.predict(x_train_res)
print ('Accuracy train:', accuracy_score(y_train_res, y_pred_KNN_train))


KeyboardInterrupt: ignored

# Finding optimum value of n_neighbours for improving accuracy for KNN using Gridsearch CV on train balanced dataset

In [ ]:
from sklearn.model_selection import GridSearchCV
import numpy

In [ ]:
n_neighbors = numpy.array(range(1,40))
param_grid = dict(n_neighbors=n_neighbors)

In [ ]:
model_1 = KNeighborsClassifier()
grid = GridSearchCV(estimator=model_1, param_grid=param_grid)
grid.fit(x_train_res, y_train_res)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])})

In [ ]:
print(grid.best_score_)
print(grid.best_params_)

0.9734649122807018
{'n_neighbors': 2}


# Random Forest 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
num_trees = 130
max_features = 4
model_RF = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
model_RF.fit(x_train_res, y_train_res)
# Test Accuracy,confusion matrix, classification report
y_pred_RF_test=model_RF.predict(x_test)
print ('Accuracy test:', accuracy_score(y_test, y_pred_RF_test))
print ('Confusion matrix test:', confusion_matrix(y_test, y_pred_RF_test))
print ('classification report test:', classification_report(y_test, y_pred_RF_test))
# Train Accuracy
y_pred_RF_train=model_RF.predict(x_train_res)
print ('Accuracy train:', accuracy_score(y_train_res, y_pred_RF_train))


Accuracy test: 0.9058823529411765
Confusion matrix test: [[287   2   0   0   0   0   0   0]
 [ 13   9   0   0   0   0   0   0]
 [  4   0   0   0   0   0   0   0]
 [  1   0   0  12   0   0   0   0]
 [  4   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0]
 [  2   1   0   0   0   0   0   0]
 [  3   0   0   0   0   0   0   0]]
classification report test:               precision    recall  f1-score   support

           0       0.91      0.99      0.95       289
           1       0.69      0.41      0.51        22
           2       0.00      0.00      0.00         4
           3       1.00      0.92      0.96        13
           4       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         3

    accuracy                           0.91       340
   macro avg       0.33      0.29      0.30       340
weighted avg       0.86      0.91     

C:\Python\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Python\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy train: 1.0


# Finding optimum value of n_estimators and max_features for improving accuracy for RF using Gridsearch CV on train balanced dataset

In [ ]:
from sklearn.model_selection import GridSearchCV
n_neighbors = np.array(range(100,150))
param_grid = dict(n_estimators=n_neighbors)
model = RandomForestClassifier()
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid.fit(x_train_res, y_train_res)
print(grid.best_score_)
print(grid.best_params_)

0.9915570175438596
{'n_estimators': 140}


In [ ]:
from sklearn.model_selection import GridSearchCV
max_features = np.array(range(1,5))
param_grid = dict(max_features=max_features)
model = RandomForestClassifier()
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid.fit(x_train_res, y_train_res)
print(grid.best_score_)
print(grid.best_params_)

0.9922149122807017
{'max_features': 3}


In [ ]:
df

SEX  INF_ANAM  STENOK_AN  FK_STENOK  IBS_POST   GB  DLIT_AG  ZSN_A  \
0       1       2.0        1.0        1.0       2.0  3.0      7.0    0.0   
1       1       1.0        0.0        0.0       0.0  0.0      0.0    0.0   
2       1       0.0        0.0        0.0       2.0  2.0      2.0    0.0   
3       0       0.0        0.0        0.0       2.0  2.0      3.0    1.0   
4       1       0.0        0.0        0.0       2.0  3.0      7.0    0.0   
...   ...       ...        ...        ...       ...  ...      ...    ...   
1695    0       0.0        4.0        2.0       1.0  2.0      7.0    0.0   
1696    0       0.0        6.0        2.0       1.0  2.0      7.0    0.0   
1697    1       3.0        6.0        2.0       2.0  0.0      0.0    0.0   
1698    0       2.0        2.0        2.0       1.0  2.0      7.0    0.0   
1699    1       2.0        0.0        2.0       2.0  2.0      0.0    4.0   

      nr_01  nr_04  ...  ANT_CA_S_n  ASP_S_n  FIBR_JELUD  A_V_BLOK  OTEK_LANC  \
0       0.0    0.0  ...         0.0      1.0           0         0          0   
1       0.0    0.0  ...         1.0      1.0           0         0          0   
2       0.0    0.0  ...         0.0      1.0           0         0          0   
3       0.0    0.0  ...         1.0      1.0           0         0          0   
4       0.0    0.0  ...         1.0      1.0           0         0          0   
...     ...    ...  ...         ...      ...         ...       ...        ...   
1695    0.0    0.0  ...         0.0      0.0           0         1          0   
1696    0.0    0.0  ...         0.0      0.0           0         0          0   
1697    0.0    0.0  ...         0.0      1.0           0         0          0   
1698    0.0    1.0  ...         1.0      1.0           0         0          1   
1699    0.0    0.0  ...         0.0      0.0           0         0          0   

      RAZRIV  ZSN  REC_IM  P_IM_STEN  LET_IS  
0          0    0       0          0       0  
1          0    0       0          0       0  
2          0    0       0          0       0  
3          0    1       0          0       0  
4          0    0       0          0       0  
...      ...  ...     ...        ...     ...  
1695       1    0       0          0       3  
1696       0    0       0          0       1  
1697       0    0       1          0       6  
1698       0    0       0          0       1  
1699       0    0       0          0       1  

[1700 rows x 54 columns]

# Testing individual models for Overall dataset

In [ ]:
array = df.values
X_overall = array[:, 0:-1]
Y_overall = array[:, -1]

In [ ]:
X_overall

array([[1., 2., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 3., 6., ..., 0., 1., 0.],
       [0., 2., 2., ..., 0., 0., 0.],
       [1., 2., 0., ..., 0., 0., 0.]])

In [ ]:
Y_overall

array([0., 0., 0., ..., 6., 1., 1.])

In [ ]:
# DT for Overall

In [ ]:
y_pred_DT_overall=dtree.predict(X_overall)
print ('Accuracy overall:', accuracy_score(Y_overall, y_pred_DT_overall))
print ('classification report overall:', classification_report(Y_overall, y_pred_DT_overall))

Accuracy overall: 0.74
classification report overall:               precision    recall  f1-score   support

         0.0       0.95      0.76      0.84      1429
         1.0       0.58      0.52      0.55       110
         2.0       0.62      0.44      0.52        18
         3.0       1.00      1.00      1.00        54
         4.0       0.54      0.83      0.66        23
         5.0       0.75      0.25      0.38        12
         6.0       0.07      0.78      0.13        27
         7.0       0.27      0.52      0.35        27

    accuracy                           0.74      1700
   macro avg       0.60      0.64      0.55      1700
weighted avg       0.89      0.74      0.80      1700



In [ ]:
# KNN for Overall

In [ ]:
y_pred_KNN_overall=model_KNN.predict(X_overall)
print ('Accuracy overall:', accuracy_score(Y_overall, y_pred_KNN_overall))
print ('classification report overall:', classification_report(Y_overall, y_pred_KNN_overall))

Accuracy overall: 0.9476470588235294
classification report overall:               precision    recall  f1-score   support

         0.0       0.98      0.97      0.97      1429
         1.0       0.89      0.87      0.88       110
         2.0       0.83      0.83      0.83        18
         3.0       0.86      0.81      0.84        54
         4.0       0.68      0.83      0.75        23
         5.0       0.56      0.83      0.67        12
         6.0       0.51      0.89      0.65        27
         7.0       0.92      0.89      0.91        27

    accuracy                           0.95      1700
   macro avg       0.78      0.87      0.81      1700
weighted avg       0.96      0.95      0.95      1700



In [ ]:
# RF for overall

In [ ]:
y_pred_RF_overall=model_RF.predict(X_overall)
print ('Accuracy overall:', accuracy_score(Y_overall, y_pred_RF_overall))
print ('classification report overall:', classification_report(Y_overall, y_pred_RF_overall))

Accuracy overall: 0.9811764705882353
classification report overall:               precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1429
         1.0       0.96      0.88      0.92       110
         2.0       1.00      0.78      0.88        18
         3.0       1.00      0.98      0.99        54
         4.0       1.00      0.83      0.90        23
         5.0       1.00      0.83      0.91        12
         6.0       1.00      0.89      0.94        27
         7.0       1.00      0.89      0.94        27

    accuracy                           0.98      1700
   macro avg       0.99      0.88      0.93      1700
weighted avg       0.98      0.98      0.98      1700



In [ ]:
df["y_pred_DT_overall"] = y_pred_DT_overall
df["y_pred_KNN_overall"] = y_pred_KNN_overall
df["y_pred_RF_overall"] = y_pred_RF_overall

In [ ]:
df.to_csv("Final_dataframe_with_predictions.csv")

# Finding From above methods RF gives high Accuracy For test,train, and also for overall dataset. So Random forest is best method for prediction and obtaining classification and is selected for final deployment.